name: app
type: 'nodejs:16'
build:
    flavor: none
variables:
    env:
        NODE_ENV: production
dependencies:
    nodejs:
        yarn: 1.22.5
hooks:
    build: |
        # Download dependencies and build Strapi.
        yarn --frozen-lockfile
        yarn build
        echo "Something"
relationships:
    database: 'dbpostgres:postgresql'
web:
    commands:
        start: yarn start
disk: 1024
mounts:
    /.cache:
        source: local
        source_path: cache
    .tmp:
        source: local
        source_path: app
    database:
        source: local
        source_path: database
    extensions:
        source: local
        source_path: extensions
    public/uploads:
        source: local
        source_path: uploads
source:
    operations:
        auto-update:
            command: |
                curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 sop-autoupdate; } 3<&0
